### ISSUE TITLE
Missing predicate file_ext:atom_phrase in current master

### ISSUE THREAD

**Issue by rla** [wouterbeek/Prolog_Library_Collection#72]
The whole warning output:

```
Warning: The predicates below are not defined. If these are defined
Warning: at runtime using assert/1, use :- dynamic Name/Arity.
Warning: 
Warning: file_ext:atom_phrase/2, which is referenced by
Warning:        /home/raivo/lib/swipl/pack/Prolog_Library_Collection/prolog/os/file_ext.pl:163:10: 1-st clause of file_ext:latest_dateTime_file/3
Warning:        /home/raivo/lib/swipl/pack/Prolog_Library_Collection/prolog/os/file_ext.pl:169:10: 1-st clause of file_ext:latest_dateTime_file/3
Warning:        /home/raivo/lib/swipl/pack/Prolog_Library_Collection/prolog/os/file_ext.pl:175:10: 1-st clause of file_ext:latest_dateTime_file/3
Warning:        /home/raivo/lib/swipl/pack/Prolog_Library_Collection/prolog/os/file_ext.pl:181:10: 1-st clause of file_ext:latest_dateTime_file/3
```

**Comment by wouterbeek** [comment]
On Mon, Sep 14, 2015 at 10:13 PM, Raivo Laanemets <notifications@github.com>
wrote:

> The whole warning output:
>
> Warning: The predicates below are not defined. If these are defined
> Warning: at runtime using assert/1, use :- dynamic Name/Arity.
> Warning:
> Warning: file_ext:atom_phrase/2, which is referenced by
> Warning:        /home/raivo/lib/swipl/pack/Prolog_Library_Collection/prolog/os/file_ext.pl:163:10: 1-st clause of file_ext:latest_dateTime_file/3
> Warning:        /home/raivo/lib/swipl/pack/Prolog_Library_Collection/prolog/os/file_ext.pl:169:10: 1-st clause of file_ext:latest_dateTime_file/3
> Warning:        /home/raivo/lib/swipl/pack/Prolog_Library_Collection/prolog/os/file_ext.pl:175:10: 1-st clause of file_ext:latest_dateTime_file/3
> Warning:        /home/raivo/lib/swipl/pack/Prolog_Library_Collection/prolog/os/file_ext.pl:181:10: 1-st clause of file_ext:latest_dateTime_file/3
>
> ​Fixed.

While the fix is trivial, is there really no way to find these missing
module imports in an automated way?

Thanks for reporting!​

---
Best regards,
Wouter Beek.

Email: me@wouterbeek.com
WWW: wouterbeek.com
Tel: +31647674624

**Comment by rla** [comment]
Not any good advises other than throughout testing (this code would just have to execute the code path with missing predicate to get the error).

Also, loading library and running make. sometimes makes these warnings immediately shown (something to do with multi-pass reference analyzer).
