### ISSUE TITLE
GUI-less env does not like gui_tracer

### ISSUE THREAD

**Issue by rla** [wouterbeek/Prolog_Library_Collection#73]
In GUI-less environment, an error is produced:

```
RROR: /app/lib/Prolog_Library_Collection/prolog/deb_ext.pl:36:
        source_sink `library(gui_tracer)' does not exist
Warning: /app/lib/Prolog_Library_Collection/prolog/deb_ext.pl:36:
        Goal (directive) failed: deb_ext:use_module(library(gui_tracer))
```

`:- guitracer.` call is commented out anyway.

**Comment by wouterbeek** [comment]
GUI-dependence is indeed something that is not wanted in this library.
I've removed references to the GUI debug tools in 016af6c561beb3af111fe6d49c8c2e3630bc7cc8
